Repository Ritikraja07/Web-Dev-Project-Hacktober, pull requests merged in 2023-10, with the labels that each got.

#2 commit
  photography page/images/1.jpg
  photography page/images/2.jpg
  photography page/images/3.jpg
  photography page/images/4.jpg
  photography page/images/5.jpg
  photography page/images/6.jpg
  photography page/images/7.jpg
  photography page/images/9.jpeg
  photography page/index.html
  photography page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#3 Create script.js
  script.js
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#5 Create variable.js
  variable.js
Labels: hacktoberfest, hacktoberfest2023, webdevelopment, hacktoberfest accepted

#7 Added react code to make a interface of app
  App.css
  App.js
  index.css
  index.js
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#6 Image Search engine using html, css and js
  Image_SearchEngine/index.html
  Image_SearchEngine/script.js
  Image_SearchEngine/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#4 Added tic-tac-toe
  tic-tac-toe/gradient-bg.jpg
  tic-tac-toe/index.html
  tic-tac-toe/index.js
  tic-tac-toe/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#8 Calculator App
  Calculator/app.js
  Calculator/index.html
  Calculator/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#9 added a matrix project
  matrix/index.html
  matrix/index.js
  matrix/style.css
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#10 Updated Readme
  README.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#12 added new game file
  ArcheryGame/index.html
  ArcheryGame/script.js
  ArcheryGame/style.css
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#13 Changes in photography page-
  photography page/app.js
  photography page/index.html
  photography page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#14 "rock paper scissor" a new project is added
  rock_paper_scissor/gradient.jpg
  rock_paper_scissor/rockpaperscissor.html
  rock_paper_scissor/script.js
  rock_paper_scissor/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#17 Added a 3-D Image Gallary
  3-D_Image_Gallary/index.html
  3-D_Image_Gallary/script.js
  3-D_Image_Gallary/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted

#16 Added an animated login page
  loginPage/index.html
  loginPage/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest accepted
